config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
get 'pages/about', to: 'pages#about'

resources :articles # Gives new article path, post to create

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  #Enforcing validation on title
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    # @article = Article.find(params[:id])
  end
  
  def update
    # Below line can be replaced with before_action at top
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Record Successfully Updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def create
    # render plain: params[:article].inspect # renders to screen
    @article = Article.new(article_params) #Need to whitelist values of Article
    if @article.save
      flash[:notice] = "Record Successfully Created"
      redirect_to article_path(@article)
    else
      #flash[:notice] = "You are dumb, try again"
      render 'new'
    end
    
    #@article.save
    #redirect_to article_path(@article)
  end
  
  def show
    # @article = Article.find(params[:id])
  end
  
  def destroy
    # First thing is you must find article, or load in what's important
    # @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Record Successfully Removed"
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
    def set_article
      @article = Article.find(params[:id])
    end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  
  end

  def about
  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<!--This is a partial.  Partial files begin with _-->

<% if @article.errors.any? %>
<h2>The following errors have occured.</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label "Notes" %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit (f.object.new_record? ? "Submit" : "Update") %>
  </p>

<% end %>

<%= link_to "Back to Animal's Records", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Record: <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Historical Animal Records</h1>
<p>
  <%= link_to "Create New Record", new_article_path %>
</p>
<table>
  <!--tr: Table Row Tag-->
  <tr>
    <!--th: Table Header Tag-->
    <th>Title</th>
    <th>Records</th>
  </tr>
  
  <!--Iterate through each element of @articles (loop), and display title and description-->
  <%  @articles.each do |article| %>
    <tr>
      <!--td: Table Data tag-->
      <td>
        <!--Referencing title and description using temporary 'article' variable-->
        <%= article.title %>
      </td>
      <td><%= article.description %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Animal Record</h1>

<!--Calls form partial-->
<%= render 'form' %>
<!--If in a different folder, we could type 'shared/form' for example-->

app/views/articles/show.html.erb
<h1>Showing Record: <%= @article.title %></h1>

<!--p tag refers to paragraph-->
<p>
  Title: <%= @article.title %>
</p>

<p>
  Notes: <%= @article.description %>
</p>

<p>
  <%= link_to "Edit this Record", edit_article_path(@article) %><br>
  <%= link_to "Back to Records", articles_path %>
</p>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
  <!--ul tag refers to Unordered List-->
  <ul>
      <!--li tag refers to List Item-->
    <li>
      <%= msg %>
    </li>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--Anything put in here will be displayed on every page!!! This is a wrapper-->
  <title>BetaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>

  <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Hi About me</h1>

<%= link_to 'Homestupsadfid', root_path %>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<%= link_to 'Records', articles_path %>

<%= link_to 'Aboutblahblah', pages_about_path %>